-- MySQL Script generated by MySQL Workbench
-- Sun Apr 15 17:20:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `addressLine1` VARCHAR(45) NOT NULL,
  `addressLine2` VARCHAR(45) NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NULL,
  `postcode` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phoneNumber` INT NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `price` INT NOT NULL,
  `quantity` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Discount` (
  `idDiscount` INT NOT NULL AUTO_INCREMENT,
  `discountAmount` INT NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDiscount`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cart` (
  `idCart` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NULL,
  `idDiscount` INT NULL,
  `totalAmount` INT NOT NULL,
  `discountedAmount` INT NULL,
  PRIMARY KEY (`idCart`),
  INDEX `idUser_idx` (`idUser` ASC),
  INDEX `idDiscount_idx` (`idDiscount` ASC),
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idDiscount`
    FOREIGN KEY (`idDiscount`)
    REFERENCES `mydb`.`Discount` (`idDiscount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CartItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CartItem` (
  `idCartItem` INT NOT NULL AUTO_INCREMENT,
  `idCart` INT NOT NULL,
  `idProduct` INT NOT NULL,
  PRIMARY KEY (`idCartItem`),
  INDEX `idCart_idx` (`idCart` ASC),
  INDEX `idProduct_idx` (`idProduct` ASC),
  CONSTRAINT `idCart`
    FOREIGN KEY (`idCart`)
    REFERENCES `mydb`.`Cart` (`idCart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProduct`
    FOREIGN KEY (`idProduct`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Currency` (
  `idCurrency` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `isoCode` VARCHAR(45) NOT NULL,
  `exchangeRateOnDollar` INT NOT NULL,
  PRIMARY KEY (`idCurrency`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrderDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrderDetails` (
  `idOrderDetails` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `addressLine1` VARCHAR(45) NOT NULL,
  `addressLine2` VARCHAR(45) NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NULL,
  `postcode` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phoneNumber` INT NOT NULL,
  PRIMARY KEY (`idOrderDetails`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PlatformLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PlatformLog` (
  `idPlatform` INT NOT NULL AUTO_INCREMENT,
  `platformName` VARCHAR(45) NULL,
  `paymentType` VARCHAR(45) NULL,
  `statusCode` VARCHAR(45) NULL,
  `statusDesc` VARCHAR(45) NULL,
  PRIMARY KEY (`idPlatform`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PaymentMethod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PaymentMethod` (
  `idPaymentMethod` INT NOT NULL AUTO_INCREMENT,
  `idPlatform` INT NOT NULL,
  `platformName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPaymentMethod`),
  INDEX `idPlatform_idx` (`idPlatform` ASC),
  CONSTRAINT `idPlatform`
    FOREIGN KEY (`idPlatform`)
    REFERENCES `mydb`.`PlatformLog` (`idPlatform`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `idCart` INT NOT NULL,
  `idCurrency` INT NOT NULL,
  `idOrderDetails` INT NULL,
  `idPaymentMethod` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `idCart_idx` (`idCart` ASC),
  INDEX `idCurrency_idx` (`idCurrency` ASC),
  INDEX `idOrderDetails_idx` (`idOrderDetails` ASC),
  INDEX `idPaymentMethod_idx` (`idPaymentMethod` ASC),
  CONSTRAINT `idCart`
    FOREIGN KEY (`idCart`)
    REFERENCES `mydb`.`Cart` (`idCart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCurrency`
    FOREIGN KEY (`idCurrency`)
    REFERENCES `mydb`.`Currency` (`idCurrency`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idOrderDetails`
    FOREIGN KEY (`idOrderDetails`)
    REFERENCES `mydb`.`OrderDetails` (`idOrderDetails`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPaymentMethod`
    FOREIGN KEY (`idPaymentMethod`)
    REFERENCES `mydb`.`PaymentMethod` (`idPaymentMethod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Refund`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Refund` (
  `idRefund` INT NOT NULL AUTO_INCREMENT,
  `idOrder` INT NOT NULL,
  `idCurrency` VARCHAR(45) NOT NULL,
  `reason` VARCHAR(255) NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`idRefund`),
  CONSTRAINT `idOrder`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Order` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCurrency`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Currency` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
